# Dataset parameters
data:
    testset_name: 'data/wind_test/test.hdf5'

    # Channels to load from data, choose from ['terrain', 'ux', 'uy', 'uz', 'turb', 'p', 'epsilon', 'nut']
    input_channels: ['terrain', 'ux', 'uy', 'uz'] # only terrain and velocities are loaded
    label_channels: ['ux', 'uy', 'uz']  # velocities

    # Get all samples in test set
    batch_test: False
    # if batch is False get the following sample in the set
    index: 11

# Optimisation parameters
optimisation:
  # 0 - wind profile optimisation, 1 - scattered points optimisation, 2 - trajectory optimisation
  optimisation_method: 1

  # Wind profile optimisation
  wind_profile: {
      optimized_corners: 4,
      rotate: 0.0, #-110.0
      polynomial_law_points: 8 #approximate wind profile using a power law
  }

  # Scattered points optimisation
  scattered_points: {
      initial_percentage: 10,
      num_steps: 45 #step percentage
  }

  # Trajectory optimisation
  trajectory: {
      x: 10,
      y: 10,
      z: 10,
      num_points: 200
  }

# NN model parameters
model:
  location: 'data/20191015_TODO/'
  name: 'ednn3d_best'
  version: 'latest'
  loss: 'MSE'