cosmo:
  file: 'data/riemenstalden/cosmo-1_ethz_fcst_2018112300.nc'        #09, 12
  time: 'auto'
  terrain_file: 'data/riemenstalden/cosmo-1_ethz_ana_const.nc'
  terrain_tiff: 'data/riemenstalden/riemenstalden_full.tif'         # fluelen_full, riemenstalden_full
  rotate: 0.0 #-110.0
  scale: 1.0  # 0.8
  prediction_prefix: ''  # rotated_

ulog:
  file: 'data/riemenstalden/14_47_05.ulg'
  filtered_file: 'data/riemenstalden/20181123_flight05_fpr_wind.hdf5'
  