cosmo:
  file: 'data/cosmo-1_ethz_fcst_2018112312.nc'        #09, 12
  time: 'auto'
  terrain_file: 'data/cosmo-1_ethz_ana_const.nc'
  terrain_tiff: 'data/riemenstalden_full.tif'         # fluelen_full, riemenstalden_full
  optimise_wind: True
  optimized_corners: 4
  rotation: 0.0 #-110.0
  scale: 1.0  # 0.8
  directional_shear: 0.0 # directional wind shear in [deg/m]
  power_law_exponent: 0.0 # vertical wind shear using a power law
  optimise_variables: ['rotation', 'scale', 'directional_shear', 'power_law_exponent'] # specify which optimisation variables will be passed to the optimiser
  prediction_prefix: ''  # rotated_

ulog:
  file: 'data/13_33_46.ulg' # 10_36_34, 11_11_57, 13_02_02, 13_33_46, 14_15_04, 14_47_05
  filtered_dir: 'data/'
  use_ekf_wind: False
  interpolation_method: 'bin'
  predict_ulog: False
  train_size: 0.8

model:
  location: 'data/20191015_TODO/'
  name: 'ednn3d_best'
  version: 'latest'
  boolean_terrain: False
  loss: 'MSE'
