measurements:
    # possible options:
    # 'cfd', 'log'
    type: 'log'

    cfd:
        filename: '/tmp/test.hdf5'
        index: 165
        kwargs: {input_mode: 5,
                 additive_gaussian_noise: True,
                 max_gaussian_noise_std: 0.2,
                 n_turb_fields: 0,
                 max_normalized_turb_scale: 0.0,
                 max_normalized_bias_scale: 0.3,
                 only_z_velocity_bias: False,
                 max_fraction_of_sparse_data: 0.1,
                 min_fraction_of_sparse_data: 0.001,
                 trajectory_min_length: 30,
                 trajectory_max_length: 300,
                 trajectory_min_segment_length: 5,
                 trajectory_max_segment_length: 20,
                 trajectory_step_size: 1.0,
                 trajectory_max_iter: 50,
                 trajectory_start_weighting_mode: 0,
                 trajectory_length_short_focus: False,
                 }

    log:
        filename: 'data/chasseral/20201128_ezg4_chasseral_flight01_fpr_wind.hdf5'
        cosmo_file: 'data/cosmo-1_ethz_ana_const.nc'
        geotiff_file: 'data/chasseral/chasseral_5.tif'
        filter_window_size: 601 # filter size of the moving average filter, no filtering if set to 0, must be uneven
        distance_field: True
        use_cosmo_grid: False
        enforce_grid_size: True
        num_cells: 64
        horizontal_overflow: 10 # number of horizontal extra cells to build the distance field
        alt_offset: 150 # offset of the takeoff position for the lower z-bound [m]
        d_horizontal: 1100 # horizontal domain extent [m]
        d_vertical: 700 # vertical domain extent [m]
        t_start: 0 # Use data from this time onwards from the log file, relative to the first timestamp (deactivated for no or negative values) [s]
        t_end: 60 # Use data up to this time from the log file, relative to the first timestamp (deactivated for no or negative values) [s]

evaluation:
    # Modes:
    # 0: Single flight, take a window as an input and predict/compare the wind for the rest of the flight along the path
    # 1: Single flight, take a sliding window as an input and predict/compare the wind for the full flight or a small window along the path
    # 2: Single flight, take a sliding window as an input and predict/compare the wind for the full flight or a small window in the binned version
    # 3: Multi flight, take a window as an input and predict/compare the wind for the rest of the flight and to the validation flight
    # 4: Single flight, take a sliding window as an input and predict/compare the wind for the full flight or a small window along the path for the validation flight
    mode: 4
    t_start: 0 # Use data from this time onwards from the log file, relative to the first timestamp (0 for negative values) [s]
    dt_input: 60 # Window size of the input for the sliding window approach [s]
    dt_pred: 60 # Window size of the prediction for the sliding window approach [s]
    compute_baseline: False
    baseline_method: 'averaging' # 'averaging', 'zero'
    full_flight: True # Indicates if for the sliding window evaluation the flight should be predicted
    cumulative: False # Indicates if for the sliding window evaluation the data from the beginning of the flight up to time t should be used
    validation_file: 'data/chasseral/20201128_ezg3_chasseral_flight01_fpr_wind.hdf5'
