# Test parameters
test:
    test_simulated_data: False
    test_flight_data: True

# CFD data
cfd:
    testset_name: 'data/wind_test/test_planning.hdf5'
    # Channels to load from data, choose from ['terrain', 'ux', 'uy', 'uz', 'turb', 'p', 'epsilon', 'nut']
    input_channels: ['terrain', 'ux', 'uy', 'uz'] # only terrain and velocities are loaded
    label_channels: ['ux', 'uy', 'uz']  # velocities
    print_names: False
    # Index of sample in the test set
    index: 63

# COSMO data
cosmo:
    file: 'data/cosmo-1_ethz_fcst_2018112312.nc'        #09, 12
    time: 'auto'
    terrain_file: 'data/cosmo-1_ethz_ana_const.nc'
    terrain_tiff: 'data/riemenstalden_full.tif'        # riemenstalden_full, fluelen_full, hinwil, tobelhof
    prediction_prefix: ''  # rotated_

# flight data
flight:
    flight_data_dir: 'data/riemenstalden/'
    files: ['20181123_flight03_fpr_wind.hdf5', '20181123_flight04_fpr_wind.hdf5', '20181123_flight05_fpr_wind.hdf5', '20181123_flight06_fpr_wind.hdf5',
    '20181123_flight01_fpr_wind.hdf5', '20181123_flight02_fpr_wind.hdf5',
    '20190411_flight01_fpr_wind.hdf5']

    # ['20181123_flight03_fpr_wind.hdf5', '20181123_flight04_fpr_wind.hdf5', '20181123_flight05_fpr_wind.hdf5', '20181123_flight06_fpr_wind.hdf5',
    #  '20181123_flight03_fpr_wind_hn.hdf5', '20181123_flight04_fpr_wind_hn.hdf5', '20181123_flight05_fpr_wind_hn.hdf5', '20181123_flight06_fpr_wind_hn.hdf5']

    # ['20181123_flight01_fpr_wind.hdf5', '20181123_flight02_fpr_wind.hdf5',
    #  '20181123_flight01_fpr_wind_hn.hdf5', '20181123_flight02_fpr_wind_hn.hdf5']

#  ['20190719_flight01_fpr_wind.hdf5',
#   '20190719_flight01_fpr_wind_hn.hdf5',
#   '20190719_flight01_fpr_wind_hn_techpod.hdf5',
#   '20190719_flight01_fpr_wind_techpod.hdf5',
#   '20190719_flight02_fpr_wind.hdf5',
#   '20190719_flight02_fpr_wind_hn.hdf5',
#   '20190726_flight01_fpr_wind_hn_techpod.hdf5',
#   '20190726_flight01_fpr_wind_techpod.hdf5',
#   '20190726_flight02_fpr_wind_hn_techpod.hdf5',
#   '20190726_flight02_fpr_wind_techpod.hdf5',
#   '20190726_flight03_fpr_wind_hn_techpod.hdf5',
#   '20190726_flight03_fpr_wind_techpod.hdf5',
#   '20190726_flight04_fpr_wind_hn_techpod.hdf5',
#   '20190726_flight04_fpr_wind_techpod.hdf5',
#   '20190726_flight05_fpr_wind_hn_techpod.hdf5',
#   '20190726_flight05_fpr_wind_techpod.hdf5',
#   '20190809_flight01_fpr_wind.hdf5',
#   '20190809_flight01_fpr_wind_hn.hdf5',
#   '20190809_flight01_fpr_wind_hn_techpod.hdf5',
#   '20190809_flight01_fpr_wind_techpod.hdf5',
#   '20190809_flight02_fpr_wind.hdf5',
#   '20190809_flight02_fpr_wind_hn.hdf5',
#   '20190809_flight02_fpr_wind_hn_techpod.hdf5',
#   '20190809_flight02_fpr_wind_techpod.hdf5',
#   '20190809_flight03_fpr_wind.hdf5',
#   '20190809_flight03_fpr_wind_hn.hdf5',
#   '20190809_flight03_fpr_wind_hn_techpod.hdf5',
#   '20190809_flight03_fpr_wind_techpod.hdf5',
#   '20190809_flight04_fpr_wind_hn_techpod.hdf5',
#   '20190809_flight04_fpr_wind_techpod.hdf5']

    # ['20190411_flight01_fpr_wind.hdf5',
    #  '20190411_flight01_fpr_wind_hn.hdf5']
    index: 0
    #
    filtered_dir: 'data/'
    use_ekf_wind: False

# Wind measurements parameters
wind:
    # Sparse points: generate random wind data by randomly sampling from the CFD labels
    sparse_data: {
        use_sparse_data: False,
        #
        percentage_of_sparse_data: 0.0005,
        terrain_percentage_correction: False,
        sample_random_region: False,
    }
    # Trajectory generation
    trajectory: {
        use_trajectory_generation: True,
        #
        trajectory_type: 'segments',  # spiral, random, segments
        #
        use_simulated_trajectory: False,
        num_points_generated: 10,
        uav_speed: 15,
        dt: 1 # seconds
    }
    # Real flight wind data
    flight: {
        predict_flight: False,
        interpolation_method: 'bin',   #'bin', 'idw', 'krigging', 'gpr'
    }

# Noise parameters
noise:
  add_turbulence: False
  add_gaussian_noise: False

# Window split parameters
window_split:
  use_window_split: True
  #
  batch_test: True
  incremental_input_prediction: True
  longterm_prediction: False
  #
  use_optimized_corners: False
  use_gpr_prediction: False
  use_krigging_prediction: False
  #
  rescale_prediction: True
  #
  window_time: 60 # seconds
  response_time: 120 # seconds
  step_time: 60 # seconds

# Corner optimisation parameters
optimisation:
    optimise_corners_individually: True
    num_of_optimisation_steps: 20
    # Rotation
    rotation: 0.0
    # Scale
    use_scale_optimisation: False
    scale: 1.0
    # Spline
    use_spline_optimisation: False
    polynomial_law_num_points: 8  #approximate wind profile using a power law
    init_wind_speed: 1.0

# NN model parameters
model:
  location: 'data/trained_models/'
  name: 'test_model_65'
  version: 'latest'
  boolean_terrain: False
  loss: 'MSE'  # L1, MSE, SoftMargin
  hybrid_model: {
      use_hybrid_model: False,
      sequence_length: 10
  }

second_model:
  use_second_model: True
  location: 'data/trained_models/'
  name: 'ednn3d_best'
  version: 'latest'
  boolean_terrain: False
  loss: 'MSE'