# Test parameters
test:
    test_simulated_data: True
    test_flight_data: False

# CFD data
cfd:
    testset_name: 'data/wind_test/test_planning.hdf5'
    # Channels to load from data, choose from ['terrain', 'ux', 'uy', 'uz', 'turb', 'p', 'epsilon', 'nut']
    input_channels: ['terrain', 'ux', 'uy', 'uz'] # only terrain and velocities are loaded
    label_channels: ['ux', 'uy', 'uz']  # velocities
    # Get all samples in test set
    batch_test: False
    # if batch is False get the following sample in the set
    index: 63

# COSMO data
cosmo:
    file: 'data/cosmo-1_ethz_fcst_2018112312.nc'        #09, 12
    time: 'auto'
    terrain_file: 'data/cosmo-1_ethz_ana_const.nc'
    terrain_tiff: 'data/riemenstalden_full.tif'        # fluelen_full, riemenstalden_full
    prediction_prefix: ''  # rotated_

# flight data
flight:
    file: 'data/14_47_05.ulg' # 10_36_34, 11_11_57, 13_02_02, 13_33_46, 14_15_04, 14_47_05   14_47_05_filtered.hdf5
    filtered_dir: 'data/'
    use_ekf_wind: False

# Wind measurements parameters
wind:
    add_wind_measurements: True
    add_corners: False

    # Sparse points: generate random wind data by randomly sampling from the CFD labels
    sparse_data: {
        use_sparse_data: False,
        percentage_of_sparse_data: 0.05,
        terrain_percentage_correction: False,
        sample_random_region: False,
    }
    # Trajectory generation
    trajectory: {
        use_trajectory_generation: True,
        num_points_generated: 100,
        uav_speed: 15,
        dt: 0.1 # seconds
    }
    # Real flight wind data
    flight: {
        predict_flight: False,
        interpolation_method: 'bin',   #['bin', 'idw', 'krigging']
    }

# Noise parameters
noise:
  generate_turbulence: False
  add_gaussian_noise: False

# Window split parameters
window_split:
  use_window_split: True
  window_time: 100 # seconds
  response_time: 20 # seconds
  step_time: 120 # seconds

# Corner optimisation parameters
optimisation:
    optimise_corners_individually: True
    # Rotation
    rotation: 0.0
    # Scale
    use_scale_optimisation: True
    scale: 1.0
    # Spline
    use_spline_optimisation: False
    polynomial_law_num_points: 8, #approximate wind profile using a power law
    init_wind_speed: 1.0,

# NN model parameters
model:
  location: 'data/20191015_TODO/'
  name: 'test_model_38'
  version: 'latest'
  boolean_terrain: False
  loss: 'MSE'