optimizer:
    # possible options:
    # 'SimpleStepOptimizer', Adadelta', 'Adagrad', 'Adam', 'Adamax', 'ASGD', 'SGD'
    name: 'Adam'
    kwargs: {'lr': 0.5}

loss:
    # possible options:
    # 'L1', 'MSE'
    name: 'MSE'

measurements:
    # possible options:
    # 'cfd', 'log'
    type: 'cfd'

    cfd:
        filename: '/tmp/test.hdf5'
        index: 10
        kwargs: {input_mode: 3,
                 additive_gaussian_noise: True,
                 max_gaussian_noise_std: 0.0,
                 n_turb_fields: 0,
                 max_normalized_turb_scale: 0.0,
                 max_normalized_bias_scale: 0.0,
                 only_z_velocity_bias: False,
                 max_fraction_of_sparse_data: 0.1,
                 min_fraction_of_sparse_data: 0.001,
                 }

    log:
        filename: '/tmp/fpr_wind.hdf5'
        cosmo_file: '/tmp/cosmo_ana_const.nc'
        geotiff_file: '/tmp/terrain_full.tif'
        num_cells: 64
        alt_offset: 50 # offset of the takeoff position for the lower z-bound [m]
        d_horizontal: 1100 # horizontal domain extent [m]
        d_vertical: 700 # vertical domain extent [m]



input_fn:
    # possible options:
    # 'bp_corners_1':
    #     Same boundary layer profile for all corners, optimizing scale and rotation
    # 'bp_corners_4':
    #     Separate boundary layer profile for all corners, optimizing scale and rotation
    # 'bp_corners_1_roughness':
    #     Same boundary layer profile for all corners, optimizing scale, rotation, and roughness
    type: 'bp_corners_1_roughness'
    kwargs: {
        roughness: 64 # roughness of the boundary layer [n_cells]
    }

run:
    max_iter: 100
    loss_change_threshold: 0.01
    loss_change_window: 4
    grad_threshold: 0.0001
