cosmo:
  file: 'data/cosmo-1_ethz_fcst_2018112312.nc'        #09, 12
  time: 'auto'
  terrain_file: 'data/cosmo-1_ethz_ana_const.nc'
  terrain_tiff: 'data/riemenstalden_full.tif'         # fluelen_full, riemenstalden_full
  rotate: 0.0 #-110.0
  scale: 1.0  # 0.8
  prediction_prefix: ''  # rotated_

ulog:
  file: 'data/13_33_46.ulg' # 10_36_34, 11_11_57, 13_02_02, 13_33_46, 14_15_04, 14_47_05
  filtered_dir: 'data/'
  use_ekf_wind: False

model:
  location: 'data/20191015_TODO/'
  name: 'ednn3d_best'
  version: 'latest'
  boolean_terrain: False
  loss: 'MSE'

generate_trajectory:
  x: [50,200,450]
  y: [50,350,700]
  z: [70,60,55]
  points_along_traj: 50
