optimizer:
    # possible options:
    # 'SimpleStepOptimizer', Adadelta', 'Adagrad', 'Adam', 'Adamax', 'ASGD', 'SGD'
    name: 'Adam'
    kwargs: {'lr': 0.5}

loss:
    # possible options:
    # 'L1', 'MSE'
    name: 'MSE'

measurements:
    # possible options:
    # 'cfd', 'log'
    type: 'cfd'

    cfd:
        filename: '/tmp/test.hdf5'
        index: 10
        kwargs: {input_mode: 3,
                 additive_gaussian_noise: True,
                 max_gaussian_noise_std: 0.0,
                 n_turb_fields: 0,
                 max_normalized_turb_scale: 0.0,
                 max_normalized_bias_scale: 0.0,
                 only_z_velocity_bias: False,
                 max_fraction_of_sparse_data: 0.1,
                 min_fraction_of_sparse_data: 0.001,
                 }

    log:
        name: '/tmp/test.ulog'



input_fn:
    # possible options:
    # 'bp_corners_1', 'bp_corners_4'
    type: 'bp_corners_4'
    kwargs: {
        roughness: 64 # roughness of the boundary layer [n_cells]
    }

run:
    max_iter: 100
    loss_change_threshold: 0.01
    loss_change_window: 4
    grad_threshold: 0.0001
