cosmo:
  file: 'data/riemenstalden/cosmo-1_ethz_fcst_2018112309.nc'
  time: 'auto'
  terrain_file: 'data/riemenstalden/cosmo-1_ethz_ana/cosmo-1_ethz_ana_const.nc'
  terrain_tiff: 'terrain/fluelen_full.tif'         # riemenstalden_full

ulog:
  file: 'logs/10_36_34.ulg' # 10_36_34, 11_11_57, 13_02_02, 13_33_46, 14_15_04, 14_47_05
