run:
    plot_every_n_batches: 5
    n_epochs: 500
    batchsize: 45
    num_workers: 6
    learning_rate_initial: 1.0E-4
    learning_rate_decay: 0.5
    learning_rate_decay_step_size: 100
    compute_validation_loss: True
    custom_init: False
    minibatch_epoch_loss: False

    # options to store data
    save_model: True
    save_metadata: True
    evaluate_testset: False
    warm_start: False
    save_model_every_n_epoch: 25
    save_params_hist_every_n_epoch: 100

    # loss function options
    loss_function: 0 # 0: MSE, 1: L1, 2: Gaussian-Log-Likelihood, 3: ScaledLoss, 4: DivergenceFreeLoss, 5: VelocityGradientLoss, else: MSE
    loss_kwargs: {
        # General
        loss_type: 'MSE', #MSE or L1
        exclude_terrain: True,

        # Gaussian-Log-Likelihood
        uncertainty_loss_eps: 1.0E-9,

        # ScaledLoss
        max_scale: 4,
        norm_threshold: 0.5,
        no_scaling: False,

        #DFL or VGL
        loss_scaling_factor: 500, # recommended values: 500 for DFL, 1200 for VGL (trial and error)
    }

    # solver settings
    beta1: 0.9
    beta2: 0.999
    eps: 1.0E-8
    weight_decay: 0
    amsgrad: False

data:
    # dataset parameter
    compressed: False
    trainset_name: 'data/train.tar'
    validationset_name: 'data/validation.tar'
    testset_name: 'data/test.tar'
    augmentation: True
    augmentation_mode: 1 # 0: subsampling, rotating with no interpolation, 1: subsampling, rotation with interpolation
    augmentation_kwargs: {
        subsampling: True,
        rotating: True
    }
    input_mode: 1
    stride_hor: 1
    stride_vert: 1
    uhor_scaling: 0.5
    uz_scaling: 0.1
    turbulence_scaling: 0.01
    terrain_scaling: 1.0
    use_turbulence: True
    autoscale: True

model:
    name_prefix: 'test_model'
    model_type: 'ModelEDNN3D'
    model_args: {
        n_x: 64,
        n_y: 64,
        n_z: 64,
        n_downsample_layers: 4,
        interpolation_mode: 'nearest',
        align_corners: False,
        skipping: True,
        use_terrain_mask: True,
        pooling_method: 'striding',
        use_fc_layers: True,
        fc_scaling: 8,
        use_mapping_layer: False,
        potential_flow: False,
        activation_type: 'LeakyReLU',
        activation_args: {negative_slope: 0.1},
        verbose: True,
        submodel_type: 'ModelEDNN3D',

        # uncertainty prediction params
        predict_uncertainty: False,
        uncertainty_train_mode: 'alternating',

        # uncertainty prediction params
        n_stacked: 3,
        pass_full_output: False,
        submodel_terrain_mask: False
    }