#!/bin/bash

YLO=-65.00
YHI=45.00
NY=110
DW=1

DY=$(echo "scale=2; ($YHI - $YLO) / $NY" | bc)
CY=$YLO
BASEDIR=$(pwd)
echo "Running from BASEDIR:${BASEDIR}, NY=${NY}, DY=${DY}, DW=${DW}"


SIMPLEDIR="${BASEDIR}/bolund_simpleFoam"
SNAPPYDIR="${BASEDIR}/bolund_snappyHexMesh"
GRIDDIR="${BASEDIR}/bolund_testgrid"

# Loop over CY positions
for (( i=0; i<=$NY; i++))
do
    echo -n "Current slice: Y=$CY, building mesh..."
    sed "s/YSLICE/${CY}/" $SIMPLEDIR/system/sliceDict.in > $SIMPLEDIR/system/sliceDict
    cd $SNAPPYDIR
    blockMesh > blockMesh.log
    snappyHexMesh -overwrite > snappyHexMesh.log

    cd $SIMPLEDIR
    extrudeMesh > extrudeMesh.log

    YDIR="${BASEDIR}/YS${CY}"

    mkdir $YDIR
    cd $YDIR
    cp -r $SIMPLEDIR/constant/polyMesh $YDIR
    echo " done."
    
    echo -n "Building resampled (regular) mesh for final output..."
    cd $GRIDDIR
    ./Allclean
    blockMesh > blockMesh.log
    touch testgrid.foam
    echo " done."

    # Loop over wind speeds
    for (( w=1; w<=15; w+=$DW))
    do
        WDIR="${YDIR}/W${w}"
        # Create system folder, symlinks from base case
        mkdir -p $WDIR/system
        cd $WDIR/system
        ln -s $SIMPLEDIR/system/controlDict controlDict
        ln -s $SIMPLEDIR/system/fvSolution fvSolution
        ln -s $SIMPLEDIR/system/fvSchemes fvSchemes

        # Create constant, symlink control files and polymesh
        mkdir -p $WDIR/constant
        cd $WDIR/constant
        ln -s $SIMPLEDIR/constant/transportProperties transportProperties
        ln -s $SIMPLEDIR/constant/turbulenceProperties turbulenceProperties
        ln -s $YDIR/polyMesh polyMesh
        
        # Copy initial conditions, change wind speed
        cd $WDIR
        cp -r $SIMPLEDIR/0.orig $WDIR/0
        sed -i "s/WINDSPEED/$w/" 0/include/ABLConditions
        echo -n "Case setup complete: Y=$CY, W=$w, running simpleFoam..."
        simpleFoam > simpleFoam.log
        echo " done."
        cd $WDIR
        touch bolund.foam

        echo -n "Resampling grid onto test grid..."
        printf -v CSVFILE "Y%+04.0fW%02d.csv" $CY $w
        python "${GRIDDIR}/resample.py" --case-dir $WDIR --mesh-dir $GRIDDIR --outfile $CSVFILE
        echo " done."

    done
    CY=$(echo "scale=4; $CY + $DY" | bc)
    cd $BASEDIR
done
echo "All slices complete."
