cosmo:
  file: 'windseer/test/testdata/test_cosmo.nc'
  time: 'auto'
  terrain_file: 'windseer/test/testdata/test_cosmo_terrain.nc'
  terrain_tiff: 'windseer/test/testdata/test_geotiff.tif'
  rotate: 0.0
  scale: 1.0
  prediction_prefix: ''

ulog:
  file: 'windseer/test/testdata/test_ulog.ulg'
  filtered_file: 'windseer/test/testdata/test_hdf5.hdf5'
  
