name: Unit Test
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
    container: osrf/ros:noetic-desktop
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apt update && apt install -y python3-pip
        apt install -y libgdal-dev=3.0.4+dfsg-1build3 libhdf5-dev libnetcdf-dev
        pip3 install scipy scikit-learn pyproj h5py matplotlib GDAL==3.0.4 netCDF4 tqdm pandas 
        pip3 install tensorboard pyulog interpolation mayavi mpl-scatter-density PyQt5 yapf
      shell: bash
    - name: Install Windseer Package
      working-directory: 
      run: |
        pwd
        cd $GITHUB_WORKSPACE/WindSeer
        pwd
        pip3 install .
        python3 windseer/proj_definitions/install_ch_defs.py
      shell: bash
    - name: unit_tests
      working-directory:
      run: |
        echo "Unit tests"
      shell: bash
