name: Unit Test
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
    container: osrf/ros:noetic-desktop
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apt update && apt install -y python3-pip
        apt install -y libgdal-dev=3.0.4+dfsg-1build3 libhdf5-dev libnetcdf-dev unzip
        pip3 install scipy scikit-learn pyproj h5py matplotlib GDAL==3.0.4 netCDF4 tqdm pandas 
        pip3 install tensorboard pyulog interpolation mayavi mpl-scatter-density PyQt5 yapf
      shell: bash
    - name: Install Windseer Package
      working-directory: 
      run: |
        pip3 install .
        python3 windseer/proj_definitions/install_ch_defs.py
      shell: bash
    - name: Download Testdata
      working-directory: 
      run: |
        wget http://robotics.ethz.ch/~asl-datasets/CI_WindSeerData/testdata.zip --directory-prefix windseer/test/testdata
        unzip windseer/test/testdata/testdata.zip -d windseer/test/testdata/
      shell: bash
    - name: Dataset Test
      working-directory:
      run: |
        python3 windseer/test/test_dataset.py
      shell: bash
    - name: Dataset Processing Test
      working-directory:
      run: |
        python3 windseer/test/test_dataset_processing.py
      shell: bash
