name: Unit Test
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
    container: osrf/ros:noetic-desktop
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apt update
        pip install scipy sklearn pyproj h5py matplotlib GDAL netCDF4 tqdm pandas 
        pip install tensorboard pyulog interpolation mayavi mpl-scatter-density PyQt5 yapf
    - name: Install Windseer Package
      working-directory: 
      run: |
        cd $GITHUB_WORKSPACE/windseer
        pip3 install .
        python3 windseer/proj_definitions/install_ch_defs.py
    - name: unit_tests
      working-directory:
      run: |
        echo "Unit tests"
